### ISSUE TITLE
Does the webserver part work?

### ISSUE THREAD

**Issue by samuk** [SovGVD/esp32-rover-tank#1]
Hi looking for some code to test the motors on our little BLDC skid steer: https://twitter.com/rosmorobot

We were planning to just do a Bluetooth car, but the web interface stuff looks good if it's functional?

We'd have to re-write the motor stuff, in any case, to work with SimpleFOC/ BLDC motors.

**Comment by SovGVD** [comment]
Hi @samuk 

Web part of that project create interface in browser with virtual joystick to proportionally control motors. It use WebSocket to make as fast as possible, pretty much zero lag. Keep in mind that code is pretty old, but should work.
Here is example of how it works https://www.instagram.com/sovgvd/p/B_Jc-orjb9L

**Comment by samuk** [comment]
Nice, thanks. Will see if hardware guy is up for trying it.

**Comment by samuk** [comment]
I got around to having a go. I get this:

esp32-rover-tank:37:10: fatal error: web/index.html.gz.h: No such file or directory
 #include "web/index.html.gz.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I guess I need to compress the /web folder somehow?

**Comment by SovGVD** [comment]
Hi @samuk
I made some changes to be able to build web interface, as also `index.html.gz.h` is included now. So if you pull latest `master` branch, the required file should be already in place. Good luck!

**Comment by samuk** [comment]
Thanks!

Some install notes

I got
compilation terminated.
exit status 1
NewPing.h: No such file or directory

Fixed by installing https://www.arduino.cc/reference/en/libraries/newping/ from libraries manager

Then I get
home/sam/Arduino/libraries/AsyncTCP-master/src/ESPAsyncTCPbuffer.cpp:27:10: fatal error: debug.h: No such file or directory
 #include <debug.h>
          ^~~~~~~~~
compilation terminated.

This was fixed by installing https://www.arduino.cc/reference/en/libraries/serialdebug/ from the libraries manager

I downloaded the zip from  https://github.com/me-no-dev/ESPAsyncWebServer and extracted to my libraries folder.

 fatal error: ESPAsyncTCP.h: No such file or directory
 #include "ESPAsyncTCP.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

I downloaded and extracted the zip from https://github.com/me-no-dev/AsyncTCP the error remained

So I downloaded and extracted https://github.com/me-no-dev/ESPAsyncTCP even though it's for ESP8266

I then get ESPAsyncTCPbuffer.cpp:27:10: fatal error: debug.h:

I read this https://stackoverflow.com/questions/61498846/espasyncwebserver-h-with-esp32

But I already have ESPAsyncWebServer & AsyncTCP installed
